-- BASE DE DATOS VUELOS
DROP TABLE IF EXISTS TIQUETE;

CREATE TABLE TIQUETE (
    id_tiquete INT NOT NULL AUTO_INCREMENT,
	fecha_hora_salida DATETIME NOT NULL,
	fecha_hora_llegada DATETIME NOT NULL,
	ciudad_origen VARCHAR(50) NOT NULL,
	ciudad_destino VARCHAR(50) NOT NULL,
	nombre_pasajero VARCHAR(50) NOT NULL,
	edad_pasajero INT NOT NULL,
	tiene_bodega_equipaje BOOL NOT NULL,
	precio FLOAT NOT NULL,
	fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fecha_modificacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fecha_baja DATETIME,
	CONSTRAINT PK_TIQUETE PRIMARY KEY (id_tiquete)
);